let puzzlesArray = [
	["Film Title", "The Wizard of Oz"],
	["Film Title", "Dial M for Murder"],
	["Film Title", "Monty Python and the Holy Grail"],
	["Film Title", "Raiders of the Lost Ark"],
	["Film Title", "Guess Who's Coming To Dinner"],
	["Film Title", "The Italian Job"],
	["Film Title", "Harry Potter and the Prisoner of Azkaban"],
	["Film Title", "Guardians of the Galaxy"],
	["Film Title", "Hidden Figures"],
	["Film Title", "Wonder Woman"],
	["Book Title", "A Tale of Two Cities"],
	["Book Title", "To Kill a Mockingbird"],
	["Book Title", "Charlie and the Chocolate Factory"],
	["Book Title", "Crime and Punishment"],
	["Book Title", "The Fault in Our Stars"],
	["Book Title", "The Joy Luck Club"],
	["Book Title", "Brave New World"],
	["Book Title", "I Know Why The Caged Bird Sings"],
	["Book Title", "Pride and Prejudice"],
	["Book Title", "Great Expectations"],
	["Song Title", "Bohemian Rhapsody"],
	["Song Title", "Bridge Over Troubled Water"],
	["Song Title", "Midnight Train to Georgia"],
	["Song Title", "Hotel California"],
	["Song Title", "Uptown Funk"],
	["Song Title", "Rolling in the Deep"],
	["Song Title", "Somebody That I Used To Know"],
	["Song Title", "Call Me Maybe"],
	["Song Title", "Boulevard of Broken Dreams"],
	["Song Title", "Ordinary People"],
	["Landmark", "Sydney Opera House"],
	["Landmark", "Leaning Tower of Pisa"],
	["Landmark", "Golden Gate Bridge"],
	["Landmark", "Colosseum"],
	["Landmark", "Arc de Triomphe"],
	["Landmark", "Empire State Building"],
	["Landmark", "Maccu Picchu"],
	["Landmark", "Buckingham Palace"],
	["Landmark", "Stonehenge"],
	["Landmark", "Great Wall of China"]
];

module.exports = puzzlesArray;